-- Seed teams from Formula IHU 2026 registration list so signup and admin user management have team options.
-- Idempotent: only inserts if no teams exist.

INSERT INTO public.teams (name, code, vehicle_class, university)
SELECT v.name, v.code, v.vehicle_class::public.vehicle_class, v.university
FROM (VALUES
  ('Aristotle University Racing Team Electric', 'AURTE', 'EV', 'TBD'),
  ('Poseidon Racing Team', 'PRT', 'EV', 'TBD'),
  ('Prom Racing', 'PR', 'EV', 'TBD'),
  ('Centaurus Racing Team', 'CRT', 'EV', 'TBD'),
  ('Perseus Racing', 'PRS', 'EV', 'TBD'),
  ('Democritus Racing Team', 'DRT', 'EV', 'TBD'),
  ('UoP Racing Team', 'UoP', 'EV', 'TBD'),
  ('Aristotle Racing Team', 'ART', 'EV', 'TBD'),
  ('Formula Students Technical University of Crete', 'FSTUC', 'EV', 'TBD'),
  ('Minautor Racing Team', 'MRT', 'EV', 'TBD'),
  ('Pelops Racing Team', 'PLP', 'EV', 'TBD'),
  ('fufracingteam', 'FUFR', 'EV', 'TBD'),
  ('FRTUCY', 'FRTUCY', 'EV', 'TBD'),
  ('Daedalus Racing Team', 'DRT2', 'EV', 'TBD'),
  ('BCN eMotorsport', 'BCN', 'EV', 'TBD'),
  ('Joanneum Racing Graz', 'JRG', 'EV', 'TBD'),
  ('High-Voltage Motorsports e.V.', 'HVM', 'EV', 'TBD'),
  ('TU Istanbul Racing', 'TIR', 'EV', 'TBD'),
  ('Formula Electric Belgium', 'FEB', 'EV', 'TBD'),
  ('STUBA Green Team', 'SGT', 'EV', 'TBD'),
  ('YTU Racing', 'YTU', 'EV', 'TBD'),
  ('Deefholt Dynamics e.V.', 'DDV', 'EV', 'TBD'),
  ('NTHU Racing', 'NTHU', 'EV', 'TBD'),
  ('TGU RACING', 'TGU', 'EV', 'TBD'),
  ('DTU - Self Driving Car', 'DTU', 'EV', 'TBD'),
  ('ART TU Cluj-Napoca', 'ARTCN', 'EV', 'TBD'),
  ('Team Octane Racing Electric', 'TORE', 'EV', 'TBD'),
  ('AMZ Racing', 'AMZ', 'EV', 'TBD'),
  ('Rennteam Uni Stuttgart', 'RUS', 'EV', 'TBD'),
  ('BME Motorsport', 'BME', 'EV', 'TBD'),
  ('Tampere Formula Student', 'TFS', 'EV', 'TBD'),
  ('Trakya Racing Formula Student Team', 'TRFST', 'EV', 'TBD'),
  ('UGATU Racing Team', 'UGATU', 'EV', 'TBD'),
  ('OzU Racing', 'OzU', 'EV', 'TBD'),
  ('MES Racing', 'MES', 'EV', 'TBD'),
  ('BlueStreamline', 'BLS', 'EV', 'TBD'),
  ('PGRacing Team', 'PGR', 'EV', 'TBD'),
  ('Universitas Indonesia Racing Team', 'UIRT', 'EV', 'TBD'),
  ('ENP RACING TEAM', 'ENP', 'EV', 'TBD'),
  ('Formula Student ONPU', 'FSONPU', 'EV', 'TBD'),
  ('UPB Drive', 'UPB', 'EV', 'TBD'),
  ('Universidad Europea de Madrid', 'UEM', 'EV', 'TBD'),
  ('NFS Team', 'NFS', 'EV', 'TBD'),
  ('DEU Formula Racing Team', 'DEU', 'EV', 'TBD'),
  ('IZTECH RACING', 'IZTECH', 'EV', 'TBD'),
  ('TU Brno Racing', 'TUBR', 'EV', 'TBD'),
  ('ARUS', 'ARUS', 'EV', 'TBD'),
  ('Baltic Racing Team', 'BRT', 'EV', 'TBD'),
  ('ESTACA FORMULA TEAM', 'ESTACA', 'EV', 'TBD'),
  ('TUfast Racing Team E-technology', 'TUFST', 'EV', 'TBD'),
  ('Raceyard E', 'RYE', 'EV', 'TBD'),
  ('Dynamics e.V.', 'DEV', 'EV', 'TBD'),
  ('BGRacing', 'BGR', 'EV', 'TBD'),
  ('greenBEAR', 'GBR', 'EV', 'TBD'),
  ('UniPR Racing Team', 'UPR', 'EV', 'TBD'),
  ('BlueStreamlinEV', 'BSLEV', 'EV', 'TBD'),
  ('UniNa Corse', 'UNC', 'EV', 'TBD'),
  ('E-Traxx', 'ETRX', 'EV', 'TBD'),
  ('Rennstall Esslingen', 'RSE', 'EV', 'TBD'),
  ('ENI Metz Racing Team', 'ENIM', 'EV', 'TBD'),
  ('BME Formula Racing Team', 'BMEF', 'EV', 'TBD'),
  ('FESB Racing', 'FESB', 'EV', 'TBD'),
  ('PUT Motorsport', 'PUT', 'EV', 'TBD'),
  ('UPC ecoRacing', 'UPC', 'EV', 'TBD'),
  ('Team wob-racing.', 'WOB', 'EV', 'TBD'),
  ('T.U.C. Racing e.V.', 'TUCR', 'EV', 'TBD'),
  ('Formula Student Team Weingarten', 'FSTW', 'EV', 'TBD'),
  ('BRS Motorsport', 'BRS', 'EV', 'TBD'),
  ('Bauman Racing Team', 'BRT2', 'EV', 'TBD'),
  ('Green Lion Racing', 'GLR', 'EV', 'TBD'),
  ('AU Dolphins', 'AUD', 'EV', 'TBD'),
  ('HofSpanung Motorsport e.V.', 'HSM', 'EV', 'TBD'),
  ('FS Team Tallinn', 'FSTT', 'EV', 'TBD'),
  ('Team Starcraft', 'TSC', 'EV', 'TBD'),
  ('Elefant Racing Bayreuth', 'ERB', 'EV', 'TBD'),
  ('UGRacing', 'UGR', 'EV', 'TBD'),
  ('Team Spark', 'TSP', 'EV', 'TBD'),
  ('Team Ojas Racing', 'TOR', 'EV', 'TBD'),
  ('Scuderia Mensa HS RheinMain Racing', 'SMHR', 'EV', 'TBD'),
  ('Racetech Racing Team TU Bergakademie Freiberg e.V.', 'RRTBF', 'EV', 'TBD'),
  ('TecnoCampus Motorsports', 'TCM', 'EV', 'TBD'),
  ('Dynamics UPC Manresa', 'DUM', 'EV', 'TBD'),
  ('UMD Racing e.V.', 'UMD', 'EV', 'TBD'),
  ('Riteh Racing Team', 'RRT', 'EV', 'TBD'),
  ('RUB Motorsport', 'RUB', 'EV', 'TBD'),
  ('ION Racing UiS', 'IRU', 'EV', 'TBD'),
  ('Aixtreme Racing', 'AXR', 'EV', 'TBD'),
  ('Formula Student FEUP', 'FSFEUP', 'EV', 'TBD'),
  ('STES Racing Electric', 'STES', 'EV', 'TBD'),
  ('METU Formula Racing', 'MFR', 'EV', 'TBD'),
  ('KOU Racing', 'KOU', 'EV', 'TBD'),
  ('HFS Racing Team', 'HFS', 'EV', 'TBD'),
  ('SUAS Racing', 'SUAS', 'EV', 'TBD'),
  ('e-Tech Racing', 'ETR', 'EV', 'TBD'),
  ('UH Racing', 'UHR', 'EV', 'TBD'),
  ('Team Crack Platoon', 'TCP', 'EV', 'TBD'),
  ('HSNR Racing', 'HSNR', 'EV', 'TBD'),
  ('Ignition Racing Team electric', 'IRTE', 'EV', 'TBD'),
  ('E-Motion Rennteam Aalen e.V.', 'EMRA', 'EV', 'TBD'),
  ('Blue Flash Mobility Concepts', 'BFMC', 'EV', 'TBD'),
  ('UWB eRacing Team Pilsen', 'UWB', 'EV', 'TBD'),
  ('Leiria Academic Racing Team', 'LART', 'EV', 'TBD'),
  ('Team Advantix', 'TAX', 'EV', 'TBD'),
  ('e.gnition Hamburg', 'EGH', 'EV', 'TBD'),
  ('Paul Ifrim', 'PIF', 'EV', 'TBD'),
  ('UPT Racing Team', 'UPT', 'EV', 'TBD'),
  ('Turon Motorsport', 'TM', 'EV', 'TBD'),
  ('T.U.IASI Racing', 'TUIR', 'EV', 'TBD'),
  ('ESTU Racing', 'ESTU', 'EV', 'TBD'),
  ('NED Racers Formula Student', 'NRFS', 'EV', 'TBD'),
  ('Formula UEM', 'FUEM', 'EV', 'TBD'),
  ('Togliatti Racing Team', 'TRT', 'EV', 'TBD'),
  ('Marseille Racing', 'MR', 'EV', 'TBD'),
  ('UJI Motorsport', 'UJI', 'EV', 'TBD'),
  ('TU-Sofia Racing', 'TUSR', 'EV', 'TBD'),
  ('CRT Universidad de Córdoba', 'CRTUC', 'EV', 'TBD'),
  ('NUST Formula Student Team', 'NUST', 'EV', 'TBD'),
  ('SAU FORMULA', 'SAU', 'EV', 'TBD'),
  ('Cukurova Racing', 'CR', 'EV', 'TBD'),
  ('Kingston racing', 'KRR', 'EV', 'TBD')
) AS v(name, code, vehicle_class, university)
WHERE NOT EXISTS (SELECT 1 FROM public.teams LIMIT 1);
